models:
  bert_model: facebook/bart-large-mnli
  emotion_model: j-hartmann/emotion-english-distilroberta-base
  max_text_length: 512
  model_timeout: 30.0
  sentiment_model: cardiffnlp/twitter-roberta-base-sentiment-latest
  use_gpu: true
processing:
  batch_size: 32
  enable_bert_model: true
  enable_emotion_model: true
  log_level: INFO
  max_email_length: 5000
  max_subject_length: 200
urgency:
  critical_max_confidence: 0.95
  critical_threshold: 4.0
  high_max_confidence: 0.9
  high_threshold: 2.0
  low_max_confidence: 0.8
  low_threshold: 0.5
  medium_max_confidence: 0.85
  medium_threshold: 1.0
version: '2.0'
weights:
  caps_ratio_weight: 3.0
  core_pattern_weight: 2.0
  department_signal_weight: 3.0
  exclamation_weight: 0.8
  positive_words_weight: 1.5
  secondary_pattern_weight: 1.5
